//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.586
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceDepartmentInfo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDepartmentInfo.DepartmentInfoServiceSoap")]
    public interface DepartmentInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DepartmentInfo_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DepartmentInfo_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_GetQxDepartmentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_GetQxDepartmentInfo(ref GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_GetQxDepartmentInfoV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_GetQxDepartmentInfoV(ref GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_IsExistRecordByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_IsExistRecordByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_IsExist(string strDepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_DelRecord(string strDepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmentInfo_DelDepartmentInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DepartmentInfo_DelDepartmentInfos(string[] arrStdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxDepartmentInfoEN : clsEntityBase2 {
        
        private string departmentIdField;
        
        private string departmentNameField;
        
        private string upDepartmentIdField;
        
        private string departmentTypeIdField;
        
        private string departMentId4CardField;
        
        private bool isAcademyField;
        
        private string subjectTypeIdField;
        
        private string departmentAbbrNameField;
        
        private int orderNumField;
        
        private bool isExamField;
        
        private bool inUseField;
        
        private string memoField;
        
        private int intTagField;
        
        private string strTagField;
        
        private bool isCheckPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
                this.RaisePropertyChanged("DepartmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UpDepartmentId {
            get {
                return this.upDepartmentIdField;
            }
            set {
                this.upDepartmentIdField = value;
                this.RaisePropertyChanged("UpDepartmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepartmentTypeId {
            get {
                return this.departmentTypeIdField;
            }
            set {
                this.departmentTypeIdField = value;
                this.RaisePropertyChanged("DepartmentTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DepartMentId4Card {
            get {
                return this.departMentId4CardField;
            }
            set {
                this.departMentId4CardField = value;
                this.RaisePropertyChanged("DepartMentId4Card");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsAcademy {
            get {
                return this.isAcademyField;
            }
            set {
                this.isAcademyField = value;
                this.RaisePropertyChanged("IsAcademy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SubjectTypeId {
            get {
                return this.subjectTypeIdField;
            }
            set {
                this.subjectTypeIdField = value;
                this.RaisePropertyChanged("SubjectTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DepartmentAbbrName {
            get {
                return this.departmentAbbrNameField;
            }
            set {
                this.departmentAbbrNameField = value;
                this.RaisePropertyChanged("DepartmentAbbrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsExam {
            get {
                return this.isExamField;
            }
            set {
                this.isExamField = value;
                this.RaisePropertyChanged("IsExam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool InUse {
            get {
                return this.inUseField;
            }
            set {
                this.inUseField = value;
                this.RaisePropertyChanged("InUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxDepartmentInfoEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DepartmentInfoServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceDepartmentInfo.DepartmentInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentInfoServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceDepartmentInfo.DepartmentInfoServiceSoap>, GeneralPlatform4WS.ServiceReferenceDepartmentInfo.DepartmentInfoServiceSoap {
        
        public DepartmentInfoServiceSoapClient() {
        }
        
        public DepartmentInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DepartmentInfo_GetDataSet(string strWhereCond) {
            return base.Channel.DepartmentInfo_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet DepartmentInfo_GetDataSetV(string strWhereCond) {
            return base.Channel.DepartmentInfo_GetDataSetV(strWhereCond);
        }
        
        public bool DepartmentInfo_GetQxDepartmentInfo(ref GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo) {
            return base.Channel.DepartmentInfo_GetQxDepartmentInfo(ref objDepartmentInfo);
        }
        
        public bool DepartmentInfo_GetQxDepartmentInfoV(ref GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo) {
            return base.Channel.DepartmentInfo_GetQxDepartmentInfoV(ref objDepartmentInfo);
        }
        
        public bool DepartmentInfo_IsExistRecordByCond(string strWhereCond) {
            return base.Channel.DepartmentInfo_IsExistRecordByCond(strWhereCond);
        }
        
        public bool DepartmentInfo_IsExist(string strDepartmentId) {
            return base.Channel.DepartmentInfo_IsExist(strDepartmentId);
        }
        
        public bool DepartmentInfo_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo) {
            return base.Channel.DepartmentInfo_AddNewRecordBySql2(objDepartmentInfo);
        }
        
        public bool DepartmentInfo_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo) {
            return base.Channel.DepartmentInfo_UpdateBySql2(objDepartmentInfo);
        }
        
        public bool DepartmentInfo_DelRecord(string strDepartmentId) {
            return base.Channel.DepartmentInfo_DelRecord(strDepartmentId);
        }
        
        public bool DepartmentInfo_DelDepartmentInfos(string[] arrStdId) {
            return base.Channel.DepartmentInfo_DelDepartmentInfos(arrStdId);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceDepartmentInfo.clsQxDepartmentInfoEN objDepartmentInfo) {
            return base.Channel.ExposeLogicClass(objDepartmentInfo);
        }
    }
}
