//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencevQxPrjUserRelationByRole.vQxPrjUserRelationByRoleServiceSoap")]
    public interface vQxPrjUserRelationByRoleServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjUserRelationByRole_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjUserRelationByRole_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjUserRelationByRole_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRole(ref GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN vQxPrjUserRelationByRole_GetObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRoleV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRoleV(ref GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] vQxPrjUserRelationByRole_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] vQxPrjUserRelationByRole_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long vQxPrjUserRelationByRole_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN vQxPrjUserRelationByRole_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int vQxPrjUserRelationByRole_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjUserRelationByRole_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjUserRelationByRole_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjUserRelationByRole_SerializeObjToXMLStr(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjUserRelationByRole_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjUserRelationByRole_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjUserRelationByRole_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsvQxPrjUserRelationByRoleEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string qxPrjIdField;
        
        private string identityIDField;
        
        private string roleIdField;
        
        private string roleNameField;
        
        private string prjNameField;
        
        private string userIdField;
        
        private string userNameField;
        
        private string departmentIdField;
        
        private string departmentNameField;
        
        private string userStateNameField;
        
        private string identityDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdentityID {
            get {
                return this.identityIDField;
            }
            set {
                this.identityIDField = value;
                this.RaisePropertyChanged("IdentityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("RoleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PrjName {
            get {
                return this.prjNameField;
            }
            set {
                this.prjNameField = value;
                this.RaisePropertyChanged("PrjName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
                this.RaisePropertyChanged("DepartmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserStateName {
            get {
                return this.userStateNameField;
            }
            set {
                this.userStateNameField = value;
                this.RaisePropertyChanged("UserStateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IdentityDesc {
            get {
                return this.identityDescField;
            }
            set {
                this.identityDescField = value;
                this.RaisePropertyChanged("IdentityDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsvQxPrjUserRelationByRoleEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface vQxPrjUserRelationByRoleServiceSoapChannel : GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.vQxPrjUserRelationByRoleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vQxPrjUserRelationByRoleServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.vQxPrjUserRelationByRoleServiceSoap>, GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.vQxPrjUserRelationByRoleServiceSoap {
        
        public vQxPrjUserRelationByRoleServiceSoapClient() {
        }
        
        public vQxPrjUserRelationByRoleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public vQxPrjUserRelationByRoleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vQxPrjUserRelationByRoleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vQxPrjUserRelationByRoleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet vQxPrjUserRelationByRole_GetDataSet(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet vQxPrjUserRelationByRole_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet vQxPrjUserRelationByRole_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.vQxPrjUserRelationByRole_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public bool vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRole(ref GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN) {
            return base.Channel.vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRole(ref objvQxPrjUserRelationByRoleEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN vQxPrjUserRelationByRole_GetObjBymId(long lngmId) {
            return base.Channel.vQxPrjUserRelationByRole_GetObjBymId(lngmId);
        }
        
        public bool vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRoleV(ref GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN) {
            return base.Channel.vQxPrjUserRelationByRole_GetvQxPrjUserRelationByRoleV(ref objvQxPrjUserRelationByRoleEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] vQxPrjUserRelationByRole_GetObjLst(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN[] vQxPrjUserRelationByRole_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public long vQxPrjUserRelationByRole_GetFirstID_S(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN vQxPrjUserRelationByRole_GetFirstObj_S(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjBymId(long lngmId) {
            return base.Channel.GetJSONObjBymId(lngmId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int vQxPrjUserRelationByRole_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_funGetRecCountByCond(strWhereCond);
        }
        
        public bool vQxPrjUserRelationByRole_IsExistRecord(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_IsExistRecord(strWhereCond);
        }
        
        public bool vQxPrjUserRelationByRole_IsExist(long lngmId) {
            return base.Channel.vQxPrjUserRelationByRole_IsExist(lngmId);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevQxPrjUserRelationByRole.clsvQxPrjUserRelationByRoleEN objvQxPrjUserRelationByRoleEN) {
            return base.Channel.ExposeLogicClass(objvQxPrjUserRelationByRoleEN);
        }
        
        public string vQxPrjUserRelationByRole_SerializeObjToXMLStr(long lngmId) {
            return base.Channel.vQxPrjUserRelationByRole_SerializeObjToXMLStr(lngmId);
        }
        
        public string vQxPrjUserRelationByRole_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string vQxPrjUserRelationByRole_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjUserRelationByRole_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
