//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferencevQxPrjMenus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencevQxPrjMenus.vQxPrjMenusServiceSoap")]
    public interface vQxPrjMenusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjMenus_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjMenus_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vQxPrjMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetvQxPrjMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjMenus_GetvQxPrjMenus(ref GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetObjByMenuId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN vQxPrjMenus_GetObjByMenuId(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetvQxPrjMenusV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjMenus_GetvQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] vQxPrjMenus_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] vQxPrjMenus_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjMenus_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN vQxPrjMenus_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByMenuId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByMenuId(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int vQxPrjMenus_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjMenus_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vQxPrjMenus_IsExist(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjMenus_SerializeObjToXMLStr(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjMenus_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vQxPrjMenus_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vQxPrjMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsvQxPrjMenusEN : clsEntityBase2 {
        
        private string menuIdField;
        
        private string menuNameField;
        
        private string qxPrjIdField;
        
        private string prjNameField;
        
        private string upMenuIdField;
        
        private string linkFileField;
        
        private string qsParametersField;
        
        private string imgFileField;
        
        private string roleIdField;
        
        private string roleNameField;
        
        private int orderNumField;
        
        private bool isLeafNodeField;
        
        private string menuSetIdField;
        
        private string menuSetNameField;
        
        private string menuTitleField;
        
        private string pageDispModeIdField;
        
        private string pageDispModeNameField;
        
        private bool inUseField;
        
        private string menuControlNameField;
        
        private int applicationTypeIdField;
        
        private string applicationTypeNameField;
        
        private string updDateField;
        
        private string updUserIdField;
        
        private string memoField;
        
        private string upMenuNameField;
        
        private int subMenusNumField;
        
        private int roleNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MenuId {
            get {
                return this.menuIdField;
            }
            set {
                this.menuIdField = value;
                this.RaisePropertyChanged("MenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MenuName {
            get {
                return this.menuNameField;
            }
            set {
                this.menuNameField = value;
                this.RaisePropertyChanged("MenuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PrjName {
            get {
                return this.prjNameField;
            }
            set {
                this.prjNameField = value;
                this.RaisePropertyChanged("PrjName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UpMenuId {
            get {
                return this.upMenuIdField;
            }
            set {
                this.upMenuIdField = value;
                this.RaisePropertyChanged("UpMenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LinkFile {
            get {
                return this.linkFileField;
            }
            set {
                this.linkFileField = value;
                this.RaisePropertyChanged("LinkFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string qsParameters {
            get {
                return this.qsParametersField;
            }
            set {
                this.qsParametersField = value;
                this.RaisePropertyChanged("qsParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ImgFile {
            get {
                return this.imgFileField;
            }
            set {
                this.imgFileField = value;
                this.RaisePropertyChanged("ImgFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("RoleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsLeafNode {
            get {
                return this.isLeafNodeField;
            }
            set {
                this.isLeafNodeField = value;
                this.RaisePropertyChanged("IsLeafNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string MenuSetId {
            get {
                return this.menuSetIdField;
            }
            set {
                this.menuSetIdField = value;
                this.RaisePropertyChanged("MenuSetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string MenuSetName {
            get {
                return this.menuSetNameField;
            }
            set {
                this.menuSetNameField = value;
                this.RaisePropertyChanged("MenuSetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string MenuTitle {
            get {
                return this.menuTitleField;
            }
            set {
                this.menuTitleField = value;
                this.RaisePropertyChanged("MenuTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PageDispModeId {
            get {
                return this.pageDispModeIdField;
            }
            set {
                this.pageDispModeIdField = value;
                this.RaisePropertyChanged("PageDispModeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PageDispModeName {
            get {
                return this.pageDispModeNameField;
            }
            set {
                this.pageDispModeNameField = value;
                this.RaisePropertyChanged("PageDispModeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool InUse {
            get {
                return this.inUseField;
            }
            set {
                this.inUseField = value;
                this.RaisePropertyChanged("InUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string MenuControlName {
            get {
                return this.menuControlNameField;
            }
            set {
                this.menuControlNameField = value;
                this.RaisePropertyChanged("MenuControlName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int ApplicationTypeId {
            get {
                return this.applicationTypeIdField;
            }
            set {
                this.applicationTypeIdField = value;
                this.RaisePropertyChanged("ApplicationTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ApplicationTypeName {
            get {
                return this.applicationTypeNameField;
            }
            set {
                this.applicationTypeNameField = value;
                this.RaisePropertyChanged("ApplicationTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string UpdDate {
            get {
                return this.updDateField;
            }
            set {
                this.updDateField = value;
                this.RaisePropertyChanged("UpdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string UpdUserId {
            get {
                return this.updUserIdField;
            }
            set {
                this.updUserIdField = value;
                this.RaisePropertyChanged("UpdUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UpMenuName {
            get {
                return this.upMenuNameField;
            }
            set {
                this.upMenuNameField = value;
                this.RaisePropertyChanged("UpMenuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int SubMenusNum {
            get {
                return this.subMenusNumField;
            }
            set {
                this.subMenusNumField = value;
                this.RaisePropertyChanged("SubMenusNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int RoleNum {
            get {
                return this.roleNumField;
            }
            set {
                this.roleNumField = value;
                this.RaisePropertyChanged("RoleNum");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsvQxPrjMenusEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface vQxPrjMenusServiceSoapChannel : GeneralPlatform4WS.ServiceReferencevQxPrjMenus.vQxPrjMenusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vQxPrjMenusServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferencevQxPrjMenus.vQxPrjMenusServiceSoap>, GeneralPlatform4WS.ServiceReferencevQxPrjMenus.vQxPrjMenusServiceSoap {
        
        public vQxPrjMenusServiceSoapClient() {
        }
        
        public vQxPrjMenusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public vQxPrjMenusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vQxPrjMenusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vQxPrjMenusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet vQxPrjMenus_GetDataSet(string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet vQxPrjMenus_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet vQxPrjMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.vQxPrjMenus_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public bool vQxPrjMenus_GetvQxPrjMenus(ref GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN) {
            return base.Channel.vQxPrjMenus_GetvQxPrjMenus(ref objvQxPrjMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN vQxPrjMenus_GetObjByMenuId(string strMenuId) {
            return base.Channel.vQxPrjMenus_GetObjByMenuId(strMenuId);
        }
        
        public bool vQxPrjMenus_GetvQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN) {
            return base.Channel.vQxPrjMenus_GetvQxPrjMenusV(ref objvQxPrjMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] vQxPrjMenus_GetObjLst(string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN[] vQxPrjMenus_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public string vQxPrjMenus_GetFirstID_S(string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN vQxPrjMenus_GetFirstObj_S(string strWhereCond) {
            return base.Channel.vQxPrjMenus_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByMenuId(string strMenuId) {
            return base.Channel.GetJSONObjByMenuId(strMenuId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int vQxPrjMenus_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.vQxPrjMenus_funGetRecCountByCond(strWhereCond);
        }
        
        public bool vQxPrjMenus_IsExistRecord(string strWhereCond) {
            return base.Channel.vQxPrjMenus_IsExistRecord(strWhereCond);
        }
        
        public bool vQxPrjMenus_IsExist(string strMenuId) {
            return base.Channel.vQxPrjMenus_IsExist(strMenuId);
        }
        
        public GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevQxPrjMenus.clsvQxPrjMenusEN objvQxPrjMenusEN) {
            return base.Channel.ExposeLogicClass(objvQxPrjMenusEN);
        }
        
        public string vQxPrjMenus_SerializeObjToXMLStr(string strMenuId) {
            return base.Channel.vQxPrjMenus_SerializeObjToXMLStr(strMenuId);
        }
        
        public string vQxPrjMenus_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.vQxPrjMenus_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string vQxPrjMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.vQxPrjMenus_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
