//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxUserMenus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxUserMenus.QxUserMenusServiceSoap")]
    public interface QxUserMenusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserMenus_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserMenus_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserMenus_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetQxUserMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_GetQxUserMenus(ref GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN QxUserMenus_GetObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetQxUserMenusV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_GetQxUserMenusV(ref GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] QxUserMenus_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] QxUserMenus_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long QxUserMenus_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN QxUserMenus_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserMenus_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_AddNewRecordBySql2ByJSON(string strQxUserMenusJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_AddNewRecordBySql2WithReturnKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserMenus_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_AddNewRecordBySql_XML(string strQxUserMenusObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_UpdateBySql2ByJSON(string strQxUserMenusJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserMenus_UpdateBySql_XML(string strQxUserMenusObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserMenus_DelRecord(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_DelQxUserMenuss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserMenus_DelQxUserMenuss(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_DelQxUserMenussByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserMenus_DelQxUserMenussByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserMenus_SerializeObjToXMLStr(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserMenus_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserMenus_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxUserMenusEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string userIdField;
        
        private string qxPrjIdField;
        
        private bool isUseRoleMenuField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsUseRoleMenu {
            get {
                return this.isUseRoleMenuField;
            }
            set {
                this.isUseRoleMenuField = value;
                this.RaisePropertyChanged("IsUseRoleMenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxUserMenusEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxUserMenusServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxUserMenus.QxUserMenusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxUserMenusServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxUserMenus.QxUserMenusServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxUserMenus.QxUserMenusServiceSoap {
        
        public QxUserMenusServiceSoapClient() {
        }
        
        public QxUserMenusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxUserMenusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserMenusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserMenusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxUserMenus_GetDataSet(string strWhereCond) {
            return base.Channel.QxUserMenus_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxUserMenus_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserMenus_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxUserMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxUserMenus_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxUserMenus_GetDataSetV(string strWhereCond) {
            return base.Channel.QxUserMenus_GetDataSetV(strWhereCond);
        }
        
        public bool QxUserMenus_GetQxUserMenus(ref GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.QxUserMenus_GetQxUserMenus(ref objQxUserMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN QxUserMenus_GetObjBymId(long lngmId) {
            return base.Channel.QxUserMenus_GetObjBymId(lngmId);
        }
        
        public bool QxUserMenus_GetQxUserMenusV(ref GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.QxUserMenus_GetQxUserMenusV(ref objQxUserMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] QxUserMenus_GetObjLst(string strWhereCond) {
            return base.Channel.QxUserMenus_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN[] QxUserMenus_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserMenus_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public long QxUserMenus_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxUserMenus_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN QxUserMenus_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxUserMenus_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjBymId(long lngmId) {
            return base.Channel.GetJSONObjBymId(lngmId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxUserMenus_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxUserMenus_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxUserMenus_IsExistRecord(string strWhereCond) {
            return base.Channel.QxUserMenus_IsExistRecord(strWhereCond);
        }
        
        public bool QxUserMenus_IsExist(long lngmId) {
            return base.Channel.QxUserMenus_IsExist(lngmId);
        }
        
        public bool QxUserMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.QxUserMenus_AddNewRecordBySql2(objQxUserMenusEN);
        }
        
        public bool QxUserMenus_AddNewRecordBySql2ByJSON(string strQxUserMenusJSONObj) {
            return base.Channel.QxUserMenus_AddNewRecordBySql2ByJSON(strQxUserMenusJSONObj);
        }
        
        public string QxUserMenus_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.QxUserMenus_AddNewRecordBySql2WithReturnKey(objQxUserMenusEN);
        }
        
        public bool QxUserMenus_AddNewRecordBySql_XML(string strQxUserMenusObjXml) {
            return base.Channel.QxUserMenus_AddNewRecordBySql_XML(strQxUserMenusObjXml);
        }
        
        public bool QxUserMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.QxUserMenus_UpdateBySql2(objQxUserMenusEN);
        }
        
        public bool QxUserMenus_UpdateBySql2ByJSON(string strQxUserMenusJSONObj) {
            return base.Channel.QxUserMenus_UpdateBySql2ByJSON(strQxUserMenusJSONObj);
        }
        
        public bool QxUserMenus_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN, string strWhereCond) {
            return base.Channel.QxUserMenus_UpdateBySqlWithCondition(objQxUserMenusEN, strWhereCond);
        }
        
        public bool QxUserMenus_UpdateBySql_XML(string strQxUserMenusObjXml) {
            return base.Channel.QxUserMenus_UpdateBySql_XML(strQxUserMenusObjXml);
        }
        
        public int QxUserMenus_DelRecord(long lngmId) {
            return base.Channel.QxUserMenus_DelRecord(lngmId);
        }
        
        public int QxUserMenus_DelQxUserMenuss(string strJSON4Keys) {
            return base.Channel.QxUserMenus_DelQxUserMenuss(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxUserMenus_DelQxUserMenussByCond(string strWhereCond) {
            return base.Channel.QxUserMenus_DelQxUserMenussByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserMenus.clsQxUserMenusEN objQxUserMenusEN) {
            return base.Channel.ExposeLogicClass(objQxUserMenusEN);
        }
        
        public string QxUserMenus_SerializeObjToXMLStr(long lngmId) {
            return base.Channel.QxUserMenus_SerializeObjToXMLStr(lngmId);
        }
        
        public string QxUserMenus_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxUserMenus_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxUserMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserMenus_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
