//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferencevUserRoleRelation {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencevUserRoleRelation.vUserRoleRelationServiceSoap")]
    public interface vUserRoleRelationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vUserRoleRelation_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet vUserRoleRelation_GetDataSetByRange(string strWhereCond, long lngMinNum, long lngMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetvUserRoleRelation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vUserRoleRelation_GetvUserRoleRelation(ref GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetvUserRoleRelationBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN vUserRoleRelation_GetvUserRoleRelationBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetvUserRoleRelationV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vUserRoleRelation_GetvUserRoleRelationV(ref GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetvUserRoleRelationObjList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN[] vUserRoleRelation_GetvUserRoleRelationObjList(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long vUserRoleRelation_GetFirstID_S(string strCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_GetFirstvUserRoleRelation_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN vUserRoleRelation_GetFirstvUserRoleRelation_S(string strCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vUserRoleRelation_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool vUserRoleRelation_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vUserRoleRelation_SerializeObjToXMLStr(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vUserRoleRelation_SerializeObjListToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string vUserRoleRelation_SerializeObjListToXMLStr(string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsvQxUserRoleRelationEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string userIdField;
        
        private string userNameField;
        
        private string departmentIdField;
        
        private string departmentNameField;
        
        private string userStateIdField;
        
        private string userStateNameField;
        
        private string roleIdField;
        
        private string roleNameField;
        
        private string prjIdField;
        
        private string prjNameField;
        
        private string memoField;
        
        private int intTagField;
        
        private string strTagField;
        
        private bool isCheckPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
                this.RaisePropertyChanged("DepartmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserStateId {
            get {
                return this.userStateIdField;
            }
            set {
                this.userStateIdField = value;
                this.RaisePropertyChanged("UserStateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserStateName {
            get {
                return this.userStateNameField;
            }
            set {
                this.userStateNameField = value;
                this.RaisePropertyChanged("UserStateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("RoleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PrjId {
            get {
                return this.prjIdField;
            }
            set {
                this.prjIdField = value;
                this.RaisePropertyChanged(clsQxProjectsEN.con_QxPrjId);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PrjName {
            get {
                return this.prjNameField;
            }
            set {
                this.prjNameField = value;
                this.RaisePropertyChanged("PrjName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsvQxUserRoleRelationEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface vUserRoleRelationServiceSoapChannel : GeneralPlatform4WS.ServiceReferencevUserRoleRelation.vUserRoleRelationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vUserRoleRelationServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferencevUserRoleRelation.vUserRoleRelationServiceSoap>, GeneralPlatform4WS.ServiceReferencevUserRoleRelation.vUserRoleRelationServiceSoap {
        
        public vUserRoleRelationServiceSoapClient() {
        }
        
        public vUserRoleRelationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public vUserRoleRelationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vUserRoleRelationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vUserRoleRelationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet vUserRoleRelation_GetDataSet(string strWhereCond) {
            return base.Channel.vUserRoleRelation_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet vUserRoleRelation_GetDataSetByRange(string strWhereCond, long lngMinNum, long lngMaxNum) {
            return base.Channel.vUserRoleRelation_GetDataSetByRange(strWhereCond, lngMinNum, lngMaxNum);
        }
        
        public bool vUserRoleRelation_GetvUserRoleRelation(ref GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN) {
            return base.Channel.vUserRoleRelation_GetvUserRoleRelation(ref objvUserRoleRelationEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN vUserRoleRelation_GetvUserRoleRelationBymId(long lngmId) {
            return base.Channel.vUserRoleRelation_GetvUserRoleRelationBymId(lngmId);
        }
        
        public bool vUserRoleRelation_GetvUserRoleRelationV(ref GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN) {
            return base.Channel.vUserRoleRelation_GetvUserRoleRelationV(ref objvUserRoleRelationEN);
        }
        
        public GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN[] vUserRoleRelation_GetvUserRoleRelationObjList(string strWhereCond) {
            return base.Channel.vUserRoleRelation_GetvUserRoleRelationObjList(strWhereCond);
        }
        
        public long vUserRoleRelation_GetFirstID_S(string strCondition) {
            return base.Channel.vUserRoleRelation_GetFirstID_S(strCondition);
        }
        
        public GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN vUserRoleRelation_GetFirstvUserRoleRelation_S(string strCondition) {
            return base.Channel.vUserRoleRelation_GetFirstvUserRoleRelation_S(strCondition);
        }
        
        public bool vUserRoleRelation_IsExistRecord(string strWhereCond) {
            return base.Channel.vUserRoleRelation_IsExistRecord(strWhereCond);
        }
        
        public bool vUserRoleRelation_IsExist(long lngmId) {
            return base.Channel.vUserRoleRelation_IsExist(lngmId);
        }
        
        public GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencevUserRoleRelation.clsvQxUserRoleRelationEN objvUserRoleRelationEN) {
            return base.Channel.ExposeLogicClass(objvUserRoleRelationEN);
        }
        
        public string vUserRoleRelation_SerializeObjToXMLStr(long lngmId) {
            return base.Channel.vUserRoleRelation_SerializeObjToXMLStr(lngmId);
        }
        
        public string vUserRoleRelation_SerializeObjListToXMLStr(string strWhereCond) {
            return base.Channel.vUserRoleRelation_SerializeObjListToXMLStr(strWhereCond);
        }
    }
}
