//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxProjects {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxProjects.QxProjectsServiceSoap")]
    public interface QxProjectsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxProjects_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxProjects_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxProjects_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxProjects_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetQxProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_GetQxProjects(ref GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetObjByQxPrjId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN QxProjects_GetObjByQxPrjId(string strQxPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetQxProjectsV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_GetQxProjectsV(ref GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] QxProjects_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] QxProjects_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN QxProjects_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByQxPrjId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByQxPrjId(string strQxPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxProjects_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_IsExist(string strQxPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_GetMaxStrIdByPrefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_GetMaxStrIdByPrefix(string strPrefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_AddNewRecordBySql2ByJSON(string strQxProjectsJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_AddNewRecordBySql_XML(string strQxProjectsObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_UpdateBySql2ByJSON(string strQxProjectsJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxProjects_UpdateBySql_XML(string strQxProjectsObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxProjects_DelRecord(string strQxPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_DelQxProjectss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxProjects_DelQxProjectss(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_DelQxProjectssByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxProjects_DelQxProjectssByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_SerializeObjToXMLStr(string strQxPrjId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxProjects_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxProjects_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxProjectsEN : clsEntityBase2 {
        
        private string qxPrjIdField;
        
        private string prjNameField;
        
        private string prjDomainField;
        
        private bool isDefaultPrjField;
        
        private string qxPrjDataBaseIdField;
        
        private string updDateField;
        
        private string updUserField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PrjName {
            get {
                return this.prjNameField;
            }
            set {
                this.prjNameField = value;
                this.RaisePropertyChanged("PrjName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrjDomain {
            get {
                return this.prjDomainField;
            }
            set {
                this.prjDomainField = value;
                this.RaisePropertyChanged("PrjDomain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDefaultPrj {
            get {
                return this.isDefaultPrjField;
            }
            set {
                this.isDefaultPrjField = value;
                this.RaisePropertyChanged("IsDefaultPrj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QxPrjDataBaseId {
            get {
                return this.qxPrjDataBaseIdField;
            }
            set {
                this.qxPrjDataBaseIdField = value;
                this.RaisePropertyChanged("QxPrjDataBaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UpdDate {
            get {
                return this.updDateField;
            }
            set {
                this.updDateField = value;
                this.RaisePropertyChanged("UpdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UpdUser {
            get {
                return this.updUserField;
            }
            set {
                this.updUserField = value;
                this.RaisePropertyChanged("UpdUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxProjectsEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxProjectsServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxProjects.QxProjectsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxProjectsServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxProjects.QxProjectsServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxProjects.QxProjectsServiceSoap {
        
        public QxProjectsServiceSoapClient() {
        }
        
        public QxProjectsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxProjectsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxProjectsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxProjectsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxProjects_GetDataSet(string strWhereCond) {
            return base.Channel.QxProjects_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxProjects_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxProjects_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxProjects_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxProjects_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxProjects_GetDataSetV(string strWhereCond) {
            return base.Channel.QxProjects_GetDataSetV(strWhereCond);
        }
        
        public bool QxProjects_GetQxProjects(ref GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN) {
            return base.Channel.QxProjects_GetQxProjects(ref objQxProjectsEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN QxProjects_GetObjByQxPrjId(string strQxPrjId) {
            return base.Channel.QxProjects_GetObjByQxPrjId(strQxPrjId);
        }
        
        public bool QxProjects_GetQxProjectsV(ref GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN) {
            return base.Channel.QxProjects_GetQxProjectsV(ref objQxProjectsEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] QxProjects_GetObjLst(string strWhereCond) {
            return base.Channel.QxProjects_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN[] QxProjects_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxProjects_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public string QxProjects_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxProjects_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN QxProjects_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxProjects_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByQxPrjId(string strQxPrjId) {
            return base.Channel.GetJSONObjByQxPrjId(strQxPrjId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxProjects_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxProjects_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxProjects_IsExistRecord(string strWhereCond) {
            return base.Channel.QxProjects_IsExistRecord(strWhereCond);
        }
        
        public bool QxProjects_IsExist(string strQxPrjId) {
            return base.Channel.QxProjects_IsExist(strQxPrjId);
        }
        
        public string QxProjects_GetMaxStrId() {
            return base.Channel.QxProjects_GetMaxStrId();
        }
        
        public string QxProjects_GetMaxStrIdByPrefix(string strPrefix) {
            return base.Channel.QxProjects_GetMaxStrIdByPrefix(strPrefix);
        }
        
        public bool QxProjects_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN) {
            return base.Channel.QxProjects_AddNewRecordBySql2(objQxProjectsEN);
        }
        
        public bool QxProjects_AddNewRecordBySql2ByJSON(string strQxProjectsJSONObj) {
            return base.Channel.QxProjects_AddNewRecordBySql2ByJSON(strQxProjectsJSONObj);
        }
        
        public bool QxProjects_AddNewRecordBySql_XML(string strQxProjectsObjXml) {
            return base.Channel.QxProjects_AddNewRecordBySql_XML(strQxProjectsObjXml);
        }
        
        public bool QxProjects_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN) {
            return base.Channel.QxProjects_UpdateBySql2(objQxProjectsEN);
        }
        
        public bool QxProjects_UpdateBySql2ByJSON(string strQxProjectsJSONObj) {
            return base.Channel.QxProjects_UpdateBySql2ByJSON(strQxProjectsJSONObj);
        }
        
        public bool QxProjects_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN, string strWhereCond) {
            return base.Channel.QxProjects_UpdateBySqlWithCondition(objQxProjectsEN, strWhereCond);
        }
        
        public bool QxProjects_UpdateBySql_XML(string strQxProjectsObjXml) {
            return base.Channel.QxProjects_UpdateBySql_XML(strQxProjectsObjXml);
        }
        
        public int QxProjects_DelRecord(string strQxPrjId) {
            return base.Channel.QxProjects_DelRecord(strQxPrjId);
        }
        
        public int QxProjects_DelQxProjectss(string strJSON4Keys) {
            return base.Channel.QxProjects_DelQxProjectss(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxProjects_DelQxProjectssByCond(string strWhereCond) {
            return base.Channel.QxProjects_DelQxProjectssByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxProjects.clsQxProjectsEN objQxProjectsEN) {
            return base.Channel.ExposeLogicClass(objQxProjectsEN);
        }
        
        public string QxProjects_SerializeObjToXMLStr(string strQxPrjId) {
            return base.Channel.QxProjects_SerializeObjToXMLStr(strQxPrjId);
        }
        
        public string QxProjects_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxProjects_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxProjects_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxProjects_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
