//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxPrjMenus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxPrjMenus.QxPrjMenusServiceSoap")]
    public interface QxPrjMenusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxPrjMenus_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxPrjMenus_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxPrjMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxPrjMenus_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetQxPrjMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_GetQxPrjMenus(ref GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetObjByMenuId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN QxPrjMenus_GetObjByMenuId(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetQxPrjMenusV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_GetQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] QxPrjMenus_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] QxPrjMenus_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN QxPrjMenus_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByMenuId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByMenuId(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxPrjMenus_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_IsExist(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_GetMaxStrIdByPrefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_GetMaxStrIdByPrefix(string strPrefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_AddNewRecordBySql2ByJSON(string strQxPrjMenusJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_AddNewRecordBySql_XML(string strQxPrjMenusObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_UpdateBySql2ByJSON(string strQxPrjMenusJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxPrjMenus_UpdateBySql_XML(string strQxPrjMenusObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxPrjMenus_DelRecord(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_DelQxPrjMenuss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxPrjMenus_DelQxPrjMenuss(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_DelQxPrjMenussByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxPrjMenus_DelQxPrjMenussByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_SerializeObjToXMLStr(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxPrjMenus_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxPrjMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxPrjMenusEN : clsEntityBase2 {
        
        private string menuIdField;
        
        private string menuNameField;
        
        private string qxPrjIdField;
        
        private string upMenuIdField;
        
        private string linkFileField;
        
        private string qsParametersField;
        
        private string imgFileField;
        
        private string roleIdField;
        
        private int orderNumField;
        
        private bool isLeafNodeField;
        
        private string menuSetIdField;
        
        private string menuTitleField;
        
        private string pageDispModeIdField;
        
        private bool inUseField;
        
        private string menuControlNameField;
        
        private int applicationTypeIdField;
        
        private string updDateField;
        
        private string updUserIdField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MenuId {
            get {
                return this.menuIdField;
            }
            set {
                this.menuIdField = value;
                this.RaisePropertyChanged("MenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MenuName {
            get {
                return this.menuNameField;
            }
            set {
                this.menuNameField = value;
                this.RaisePropertyChanged("MenuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UpMenuId {
            get {
                return this.upMenuIdField;
            }
            set {
                this.upMenuIdField = value;
                this.RaisePropertyChanged("UpMenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LinkFile {
            get {
                return this.linkFileField;
            }
            set {
                this.linkFileField = value;
                this.RaisePropertyChanged("LinkFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string qsParameters {
            get {
                return this.qsParametersField;
            }
            set {
                this.qsParametersField = value;
                this.RaisePropertyChanged("qsParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImgFile {
            get {
                return this.imgFileField;
            }
            set {
                this.imgFileField = value;
                this.RaisePropertyChanged("ImgFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsLeafNode {
            get {
                return this.isLeafNodeField;
            }
            set {
                this.isLeafNodeField = value;
                this.RaisePropertyChanged("IsLeafNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MenuSetId {
            get {
                return this.menuSetIdField;
            }
            set {
                this.menuSetIdField = value;
                this.RaisePropertyChanged("MenuSetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MenuTitle {
            get {
                return this.menuTitleField;
            }
            set {
                this.menuTitleField = value;
                this.RaisePropertyChanged("MenuTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PageDispModeId {
            get {
                return this.pageDispModeIdField;
            }
            set {
                this.pageDispModeIdField = value;
                this.RaisePropertyChanged("PageDispModeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool InUse {
            get {
                return this.inUseField;
            }
            set {
                this.inUseField = value;
                this.RaisePropertyChanged("InUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string MenuControlName {
            get {
                return this.menuControlNameField;
            }
            set {
                this.menuControlNameField = value;
                this.RaisePropertyChanged("MenuControlName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ApplicationTypeId {
            get {
                return this.applicationTypeIdField;
            }
            set {
                this.applicationTypeIdField = value;
                this.RaisePropertyChanged("ApplicationTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UpdDate {
            get {
                return this.updDateField;
            }
            set {
                this.updDateField = value;
                this.RaisePropertyChanged("UpdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UpdUserId {
            get {
                return this.updUserIdField;
            }
            set {
                this.updUserIdField = value;
                this.RaisePropertyChanged("UpdUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxPrjMenusEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxPrjMenusServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxPrjMenus.QxPrjMenusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxPrjMenusServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxPrjMenus.QxPrjMenusServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxPrjMenus.QxPrjMenusServiceSoap {
        
        public QxPrjMenusServiceSoapClient() {
        }
        
        public QxPrjMenusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxPrjMenusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxPrjMenusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxPrjMenusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxPrjMenus_GetDataSet(string strWhereCond) {
            return base.Channel.QxPrjMenus_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxPrjMenus_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxPrjMenus_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxPrjMenus_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxPrjMenus_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxPrjMenus_GetDataSetV(string strWhereCond) {
            return base.Channel.QxPrjMenus_GetDataSetV(strWhereCond);
        }
        
        public bool QxPrjMenus_GetQxPrjMenus(ref GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN) {
            return base.Channel.QxPrjMenus_GetQxPrjMenus(ref objQxPrjMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN QxPrjMenus_GetObjByMenuId(string strMenuId) {
            return base.Channel.QxPrjMenus_GetObjByMenuId(strMenuId);
        }
        
        public bool QxPrjMenus_GetQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN) {
            return base.Channel.QxPrjMenus_GetQxPrjMenusV(ref objQxPrjMenusEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] QxPrjMenus_GetObjLst(string strWhereCond) {
            return base.Channel.QxPrjMenus_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN[] QxPrjMenus_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxPrjMenus_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public string QxPrjMenus_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxPrjMenus_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN QxPrjMenus_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxPrjMenus_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByMenuId(string strMenuId) {
            return base.Channel.GetJSONObjByMenuId(strMenuId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxPrjMenus_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxPrjMenus_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxPrjMenus_IsExistRecord(string strWhereCond) {
            return base.Channel.QxPrjMenus_IsExistRecord(strWhereCond);
        }
        
        public bool QxPrjMenus_IsExist(string strMenuId) {
            return base.Channel.QxPrjMenus_IsExist(strMenuId);
        }
        
        public string QxPrjMenus_GetMaxStrId() {
            return base.Channel.QxPrjMenus_GetMaxStrId();
        }
        
        public string QxPrjMenus_GetMaxStrIdByPrefix(string strPrefix) {
            return base.Channel.QxPrjMenus_GetMaxStrIdByPrefix(strPrefix);
        }
        
        public bool QxPrjMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN) {
            return base.Channel.QxPrjMenus_AddNewRecordBySql2(objQxPrjMenusEN);
        }
        
        public bool QxPrjMenus_AddNewRecordBySql2ByJSON(string strQxPrjMenusJSONObj) {
            return base.Channel.QxPrjMenus_AddNewRecordBySql2ByJSON(strQxPrjMenusJSONObj);
        }
        
        public bool QxPrjMenus_AddNewRecordBySql_XML(string strQxPrjMenusObjXml) {
            return base.Channel.QxPrjMenus_AddNewRecordBySql_XML(strQxPrjMenusObjXml);
        }
        
        public bool QxPrjMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN) {
            return base.Channel.QxPrjMenus_UpdateBySql2(objQxPrjMenusEN);
        }
        
        public bool QxPrjMenus_UpdateBySql2ByJSON(string strQxPrjMenusJSONObj) {
            return base.Channel.QxPrjMenus_UpdateBySql2ByJSON(strQxPrjMenusJSONObj);
        }
        
        public bool QxPrjMenus_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN, string strWhereCond) {
            return base.Channel.QxPrjMenus_UpdateBySqlWithCondition(objQxPrjMenusEN, strWhereCond);
        }
        
        public bool QxPrjMenus_UpdateBySql_XML(string strQxPrjMenusObjXml) {
            return base.Channel.QxPrjMenus_UpdateBySql_XML(strQxPrjMenusObjXml);
        }
        
        public int QxPrjMenus_DelRecord(string strMenuId) {
            return base.Channel.QxPrjMenus_DelRecord(strMenuId);
        }
        
        public int QxPrjMenus_DelQxPrjMenuss(string strJSON4Keys) {
            return base.Channel.QxPrjMenus_DelQxPrjMenuss(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxPrjMenus_DelQxPrjMenussByCond(string strWhereCond) {
            return base.Channel.QxPrjMenus_DelQxPrjMenussByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxPrjMenus.clsQxPrjMenusEN objQxPrjMenusEN) {
            return base.Channel.ExposeLogicClass(objQxPrjMenusEN);
        }
        
        public string QxPrjMenus_SerializeObjToXMLStr(string strMenuId) {
            return base.Channel.QxPrjMenus_SerializeObjToXMLStr(strMenuId);
        }
        
        public string QxPrjMenus_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxPrjMenus_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxPrjMenus_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxPrjMenus_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
