//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferencePrjMenus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePrjMenus.PrjMenusServiceSoap")]
    public interface PrjMenusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PrjMenus_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PrjMenus_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_GetQxPrjMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_GetQxPrjMenus(ref GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_GetQxPrjMenusV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_GetQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_IsExistRecordByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_IsExistRecordByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_IsExist(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string PrjMenus_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_DelRecord(string strMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_DelPrjMenuss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool PrjMenus_DelPrjMenuss(string[] arrStdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrjMenus_DelPrjMenussByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int PrjMenus_DelPrjMenussByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxPrjMenusEN : clsEntityBase2 {
        
        private string menuIdField;
        
        private string menuNameField;
        
        private string prjIdField;
        
        private string upMenuIdField;
        
        private string linkFileField;
        
        private string qsParametersField;
        
        private string imgFileField;
        
        private string roleIdField;
        
        private int orderNumField;
        
        private bool isLeafNodeField;
        
        private string menuSetIdField;
        
        private string menuTitleField;
        
        private string pageDispModeIdField;
        
        private string updDateField;
        
        private string updUserIdField;
        
        private string memoField;
        
        private int intTagField;
        
        private string strTagField;
        
        private bool isCheckPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MenuId {
            get {
                return this.menuIdField;
            }
            set {
                this.menuIdField = value;
                this.RaisePropertyChanged("MenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MenuName {
            get {
                return this.menuNameField;
            }
            set {
                this.menuNameField = value;
                this.RaisePropertyChanged("MenuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrjId {
            get {
                return this.prjIdField;
            }
            set {
                this.prjIdField = value;
                this.RaisePropertyChanged(clsQxProjectsEN.con_QxPrjId);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UpMenuId {
            get {
                return this.upMenuIdField;
            }
            set {
                this.upMenuIdField = value;
                this.RaisePropertyChanged("UpMenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LinkFile {
            get {
                return this.linkFileField;
            }
            set {
                this.linkFileField = value;
                this.RaisePropertyChanged("LinkFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string qsParameters {
            get {
                return this.qsParametersField;
            }
            set {
                this.qsParametersField = value;
                this.RaisePropertyChanged("qsParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ImgFile {
            get {
                return this.imgFileField;
            }
            set {
                this.imgFileField = value;
                this.RaisePropertyChanged("ImgFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OrderNum {
            get {
                return this.orderNumField;
            }
            set {
                this.orderNumField = value;
                this.RaisePropertyChanged("OrderNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsLeafNode {
            get {
                return this.isLeafNodeField;
            }
            set {
                this.isLeafNodeField = value;
                this.RaisePropertyChanged("IsLeafNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MenuSetId {
            get {
                return this.menuSetIdField;
            }
            set {
                this.menuSetIdField = value;
                this.RaisePropertyChanged("MenuSetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MenuTitle {
            get {
                return this.menuTitleField;
            }
            set {
                this.menuTitleField = value;
                this.RaisePropertyChanged("MenuTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PageDispModeId {
            get {
                return this.pageDispModeIdField;
            }
            set {
                this.pageDispModeIdField = value;
                this.RaisePropertyChanged("PageDispModeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UpdDate {
            get {
                return this.updDateField;
            }
            set {
                this.updDateField = value;
                this.RaisePropertyChanged("UpdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UpdUserId {
            get {
                return this.updUserIdField;
            }
            set {
                this.updUserIdField = value;
                this.RaisePropertyChanged("UpdUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxPrjMenusEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrjMenusServiceSoapChannel : GeneralPlatform4WS.ServiceReferencePrjMenus.PrjMenusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrjMenusServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferencePrjMenus.PrjMenusServiceSoap>, GeneralPlatform4WS.ServiceReferencePrjMenus.PrjMenusServiceSoap {
        
        public PrjMenusServiceSoapClient() {
        }
        
        public PrjMenusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrjMenusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrjMenusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrjMenusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet PrjMenus_GetDataSet(string strWhereCond) {
            return base.Channel.PrjMenus_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet PrjMenus_GetDataSetV(string strWhereCond) {
            return base.Channel.PrjMenus_GetDataSetV(strWhereCond);
        }
        
        public bool PrjMenus_GetQxPrjMenus(ref GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus) {
            return base.Channel.PrjMenus_GetQxPrjMenus(ref objPrjMenus);
        }
        
        public bool PrjMenus_GetQxPrjMenusV(ref GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus) {
            return base.Channel.PrjMenus_GetQxPrjMenusV(ref objPrjMenus);
        }
        
        public bool PrjMenus_IsExistRecordByCond(string strWhereCond) {
            return base.Channel.PrjMenus_IsExistRecordByCond(strWhereCond);
        }
        
        public bool PrjMenus_IsExist(string strMenuId) {
            return base.Channel.PrjMenus_IsExist(strMenuId);
        }
        
        public string PrjMenus_GetMaxStrId() {
            return base.Channel.PrjMenus_GetMaxStrId();
        }
        
        public bool PrjMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus) {
            return base.Channel.PrjMenus_AddNewRecordBySql2(objPrjMenus);
        }
        
        public bool PrjMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus) {
            return base.Channel.PrjMenus_UpdateBySql2(objPrjMenus);
        }
        
        public bool PrjMenus_DelRecord(string strMenuId) {
            return base.Channel.PrjMenus_DelRecord(strMenuId);
        }
        
        public bool PrjMenus_DelPrjMenuss(string[] arrStdId) {
            return base.Channel.PrjMenus_DelPrjMenuss(arrStdId);
        }
        
        public int PrjMenus_DelPrjMenussByCond(string strWhereCond) {
            return base.Channel.PrjMenus_DelPrjMenussByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferencePrjMenus.clsQxPrjMenusEN objPrjMenus) {
            return base.Channel.ExposeLogicClass(objPrjMenus);
        }
    }
}
