//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxUserGroupRelation.QxUserGroupRelationServiceSoap")]
    public interface QxUserGroupRelationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupRelation_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupRelation_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupRelation_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupRelation_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetQxUserGroupRelation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_GetQxUserGroupRelation(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN QxUserGroupRelation_GetObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetQxUserGroupRelationV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_GetQxUserGroupRelationV(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] QxUserGroupRelation_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] QxUserGroupRelation_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long QxUserGroupRelation_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN QxUserGroupRelation_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupRelation_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_AddNewRecordBySql2ByJSON(string strQxUserGroupRelationJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_AddNewRecordBySql2WithReturnKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupRelation_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_AddNewRecordBySql_XML(string strQxUserGroupRelationObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_UpdateBySql2ByJSON(string strQxUserGroupRelationJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupRelation_UpdateBySql_XML(string strQxUserGroupRelationObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupRelation_DelRecord(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_DelQxUserGroupRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupRelation_DelQxUserGroupRelations(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_DelQxUserGroupRelationsByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupRelation_DelQxUserGroupRelationsByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupRelation_SerializeObjToXMLStr(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupRelation_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupRelation_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupRelation_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxUserGroupRelationEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string userIdField;
        
        private string groupIdField;
        
        private string memoField;
        
        private string qxPrjIdField;
        
        private string manageIdField;
        
        private string manageTypeIdField;
        
        private bool isDefaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("GroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ManageId {
            get {
                return this.manageIdField;
            }
            set {
                this.manageIdField = value;
                this.RaisePropertyChanged("ManageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ManageTypeId {
            get {
                return this.manageTypeIdField;
            }
            set {
                this.manageTypeIdField = value;
                this.RaisePropertyChanged("ManageTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
                this.RaisePropertyChanged("IsDefault");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxUserGroupRelationEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxUserGroupRelationServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.QxUserGroupRelationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxUserGroupRelationServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.QxUserGroupRelationServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.QxUserGroupRelationServiceSoap {
        
        public QxUserGroupRelationServiceSoapClient() {
        }
        
        public QxUserGroupRelationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxUserGroupRelationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserGroupRelationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserGroupRelationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxUserGroupRelation_GetDataSet(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxUserGroupRelation_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxUserGroupRelation_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxUserGroupRelation_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxUserGroupRelation_GetDataSetV(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetDataSetV(strWhereCond);
        }
        
        public bool QxUserGroupRelation_GetQxUserGroupRelation(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.QxUserGroupRelation_GetQxUserGroupRelation(ref objQxUserGroupRelationEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN QxUserGroupRelation_GetObjBymId(long lngmId) {
            return base.Channel.QxUserGroupRelation_GetObjBymId(lngmId);
        }
        
        public bool QxUserGroupRelation_GetQxUserGroupRelationV(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.QxUserGroupRelation_GetQxUserGroupRelationV(ref objQxUserGroupRelationEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] QxUserGroupRelation_GetObjLst(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN[] QxUserGroupRelation_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public long QxUserGroupRelation_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN QxUserGroupRelation_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjBymId(long lngmId) {
            return base.Channel.GetJSONObjBymId(lngmId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxUserGroupRelation_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxUserGroupRelation_IsExistRecord(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_IsExistRecord(strWhereCond);
        }
        
        public bool QxUserGroupRelation_IsExist(long lngmId) {
            return base.Channel.QxUserGroupRelation_IsExist(lngmId);
        }
        
        public bool QxUserGroupRelation_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.QxUserGroupRelation_AddNewRecordBySql2(objQxUserGroupRelationEN);
        }
        
        public bool QxUserGroupRelation_AddNewRecordBySql2ByJSON(string strQxUserGroupRelationJSONObj) {
            return base.Channel.QxUserGroupRelation_AddNewRecordBySql2ByJSON(strQxUserGroupRelationJSONObj);
        }
        
        public string QxUserGroupRelation_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.QxUserGroupRelation_AddNewRecordBySql2WithReturnKey(objQxUserGroupRelationEN);
        }
        
        public bool QxUserGroupRelation_AddNewRecordBySql_XML(string strQxUserGroupRelationObjXml) {
            return base.Channel.QxUserGroupRelation_AddNewRecordBySql_XML(strQxUserGroupRelationObjXml);
        }
        
        public bool QxUserGroupRelation_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.QxUserGroupRelation_UpdateBySql2(objQxUserGroupRelationEN);
        }
        
        public bool QxUserGroupRelation_UpdateBySql2ByJSON(string strQxUserGroupRelationJSONObj) {
            return base.Channel.QxUserGroupRelation_UpdateBySql2ByJSON(strQxUserGroupRelationJSONObj);
        }
        
        public bool QxUserGroupRelation_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN, string strWhereCond) {
            return base.Channel.QxUserGroupRelation_UpdateBySqlWithCondition(objQxUserGroupRelationEN, strWhereCond);
        }
        
        public bool QxUserGroupRelation_UpdateBySql_XML(string strQxUserGroupRelationObjXml) {
            return base.Channel.QxUserGroupRelation_UpdateBySql_XML(strQxUserGroupRelationObjXml);
        }
        
        public int QxUserGroupRelation_DelRecord(long lngmId) {
            return base.Channel.QxUserGroupRelation_DelRecord(lngmId);
        }
        
        public int QxUserGroupRelation_DelQxUserGroupRelations(string strJSON4Keys) {
            return base.Channel.QxUserGroupRelation_DelQxUserGroupRelations(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxUserGroupRelation_DelQxUserGroupRelationsByCond(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_DelQxUserGroupRelationsByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserGroupRelation.clsQxUserGroupRelationEN objQxUserGroupRelationEN) {
            return base.Channel.ExposeLogicClass(objQxUserGroupRelationEN);
        }
        
        public string QxUserGroupRelation_SerializeObjToXMLStr(long lngmId) {
            return base.Channel.QxUserGroupRelation_SerializeObjToXMLStr(lngmId);
        }
        
        public string QxUserGroupRelation_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxUserGroupRelation_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxUserGroupRelation_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupRelation_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
