//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceDataBaseType {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDataBaseType.DataBaseTypeServiceSoap")]
    public interface DataBaseTypeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataBaseType_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataBaseType_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataBaseType_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataBaseType_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetDataBaseType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_GetDataBaseType(ref GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetObjByDataBaseTypeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN DataBaseType_GetObjByDataBaseTypeId(string strDataBaseTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetDataBaseTypeV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_GetDataBaseTypeV(ref GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] DataBaseType_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] DataBaseType_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN DataBaseType_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByDataBaseTypeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByDataBaseTypeId(string strDataBaseTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DataBaseType_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_IsExist(string strDataBaseTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_GetMaxStrIdByPrefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_GetMaxStrIdByPrefix(string strPrefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_AddNewRecordBySql2ByJSON(string strDataBaseTypeJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_AddNewRecordBySql_XML(string strDataBaseTypeObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_UpdateBySql2ByJSON(string strDataBaseTypeJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool DataBaseType_UpdateBySql_XML(string strDataBaseTypeObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DataBaseType_DelRecord(string strDataBaseTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_DelDataBaseTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DataBaseType_DelDataBaseTypes(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_DelDataBaseTypesByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DataBaseType_DelDataBaseTypesByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_SerializeObjToXMLStr(string strDataBaseTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataBaseType_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string DataBaseType_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsDataBaseTypeEN : clsEntityBase2 {
        
        private string dataBaseTypeIdField;
        
        private string dataBaseTypeNameField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataBaseTypeId {
            get {
                return this.dataBaseTypeIdField;
            }
            set {
                this.dataBaseTypeIdField = value;
                this.RaisePropertyChanged("DataBaseTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DataBaseTypeName {
            get {
                return this.dataBaseTypeNameField;
            }
            set {
                this.dataBaseTypeNameField = value;
                this.RaisePropertyChanged("DataBaseTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsDataBaseTypeEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBaseTypeServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceDataBaseType.DataBaseTypeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBaseTypeServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceDataBaseType.DataBaseTypeServiceSoap>, GeneralPlatform4WS.ServiceReferenceDataBaseType.DataBaseTypeServiceSoap {
        
        public DataBaseTypeServiceSoapClient() {
        }
        
        public DataBaseTypeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBaseTypeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseTypeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseTypeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DataBaseType_GetDataSet(string strWhereCond) {
            return base.Channel.DataBaseType_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet DataBaseType_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.DataBaseType_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet DataBaseType_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.DataBaseType_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet DataBaseType_GetDataSetV(string strWhereCond) {
            return base.Channel.DataBaseType_GetDataSetV(strWhereCond);
        }
        
        public bool DataBaseType_GetDataBaseType(ref GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN) {
            return base.Channel.DataBaseType_GetDataBaseType(ref objDataBaseTypeEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN DataBaseType_GetObjByDataBaseTypeId(string strDataBaseTypeId) {
            return base.Channel.DataBaseType_GetObjByDataBaseTypeId(strDataBaseTypeId);
        }
        
        public bool DataBaseType_GetDataBaseTypeV(ref GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN) {
            return base.Channel.DataBaseType_GetDataBaseTypeV(ref objDataBaseTypeEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] DataBaseType_GetObjLst(string strWhereCond) {
            return base.Channel.DataBaseType_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN[] DataBaseType_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.DataBaseType_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public string DataBaseType_GetFirstID_S(string strWhereCond) {
            return base.Channel.DataBaseType_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN DataBaseType_GetFirstObj_S(string strWhereCond) {
            return base.Channel.DataBaseType_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByDataBaseTypeId(string strDataBaseTypeId) {
            return base.Channel.GetJSONObjByDataBaseTypeId(strDataBaseTypeId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int DataBaseType_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.DataBaseType_funGetRecCountByCond(strWhereCond);
        }
        
        public bool DataBaseType_IsExistRecord(string strWhereCond) {
            return base.Channel.DataBaseType_IsExistRecord(strWhereCond);
        }
        
        public bool DataBaseType_IsExist(string strDataBaseTypeId) {
            return base.Channel.DataBaseType_IsExist(strDataBaseTypeId);
        }
        
        public string DataBaseType_GetMaxStrId() {
            return base.Channel.DataBaseType_GetMaxStrId();
        }
        
        public string DataBaseType_GetMaxStrIdByPrefix(string strPrefix) {
            return base.Channel.DataBaseType_GetMaxStrIdByPrefix(strPrefix);
        }
        
        public bool DataBaseType_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN) {
            return base.Channel.DataBaseType_AddNewRecordBySql2(objDataBaseTypeEN);
        }
        
        public bool DataBaseType_AddNewRecordBySql2ByJSON(string strDataBaseTypeJSONObj) {
            return base.Channel.DataBaseType_AddNewRecordBySql2ByJSON(strDataBaseTypeJSONObj);
        }
        
        public bool DataBaseType_AddNewRecordBySql_XML(string strDataBaseTypeObjXml) {
            return base.Channel.DataBaseType_AddNewRecordBySql_XML(strDataBaseTypeObjXml);
        }
        
        public bool DataBaseType_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN) {
            return base.Channel.DataBaseType_UpdateBySql2(objDataBaseTypeEN);
        }
        
        public bool DataBaseType_UpdateBySql2ByJSON(string strDataBaseTypeJSONObj) {
            return base.Channel.DataBaseType_UpdateBySql2ByJSON(strDataBaseTypeJSONObj);
        }
        
        public bool DataBaseType_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN, string strWhereCond) {
            return base.Channel.DataBaseType_UpdateBySqlWithCondition(objDataBaseTypeEN, strWhereCond);
        }
        
        public bool DataBaseType_UpdateBySql_XML(string strDataBaseTypeObjXml) {
            return base.Channel.DataBaseType_UpdateBySql_XML(strDataBaseTypeObjXml);
        }
        
        public int DataBaseType_DelRecord(string strDataBaseTypeId) {
            return base.Channel.DataBaseType_DelRecord(strDataBaseTypeId);
        }
        
        public int DataBaseType_DelDataBaseTypes(string strJSON4Keys) {
            return base.Channel.DataBaseType_DelDataBaseTypes(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int DataBaseType_DelDataBaseTypesByCond(string strWhereCond) {
            return base.Channel.DataBaseType_DelDataBaseTypesByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceDataBaseType.clsDataBaseTypeEN objDataBaseTypeEN) {
            return base.Channel.ExposeLogicClass(objDataBaseTypeEN);
        }
        
        public string DataBaseType_SerializeObjToXMLStr(string strDataBaseTypeId) {
            return base.Channel.DataBaseType_SerializeObjToXMLStr(strDataBaseTypeId);
        }
        
        public string DataBaseType_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.DataBaseType_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string DataBaseType_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.DataBaseType_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
