//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.586
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceSubjectRelation {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSubjectRelation.SubjectRelationServiceSoap")]
    public interface SubjectRelationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SubjectRelation_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SubjectRelation_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_GetSubjectRelation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_GetSubjectRelation(ref GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_GetSubjectRelationV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_GetSubjectRelationV(ref GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_IsExistRecordByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_IsExistRecordByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_DelRecord(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubjectRelation_DelSubjectRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool SubjectRelation_DelSubjectRelations(string[] arrStdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsSubjectRelationEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string userIdField;
        
        private string leaderIdField;
        
        private bool isDirectLeaderField;
        
        private string memoField;
        
        private int intTagField;
        
        private string strTagField;
        
        private bool isCheckPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LeaderId {
            get {
                return this.leaderIdField;
            }
            set {
                this.leaderIdField = value;
                this.RaisePropertyChanged("LeaderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDirectLeader {
            get {
                return this.isDirectLeaderField;
            }
            set {
                this.isDirectLeaderField = value;
                this.RaisePropertyChanged("IsDirectLeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsSubjectRelationEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubjectRelationServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceSubjectRelation.SubjectRelationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubjectRelationServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceSubjectRelation.SubjectRelationServiceSoap>, GeneralPlatform4WS.ServiceReferenceSubjectRelation.SubjectRelationServiceSoap {
        
        public SubjectRelationServiceSoapClient() {
        }
        
        public SubjectRelationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubjectRelationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectRelationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubjectRelationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SubjectRelation_GetDataSet(string strWhereCond) {
            return base.Channel.SubjectRelation_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet SubjectRelation_GetDataSetV(string strWhereCond) {
            return base.Channel.SubjectRelation_GetDataSetV(strWhereCond);
        }
        
        public bool SubjectRelation_GetSubjectRelation(ref GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation) {
            return base.Channel.SubjectRelation_GetSubjectRelation(ref objSubjectRelation);
        }
        
        public bool SubjectRelation_GetSubjectRelationV(ref GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation) {
            return base.Channel.SubjectRelation_GetSubjectRelationV(ref objSubjectRelation);
        }
        
        public bool SubjectRelation_IsExistRecordByCond(string strWhereCond) {
            return base.Channel.SubjectRelation_IsExistRecordByCond(strWhereCond);
        }
        
        public bool SubjectRelation_IsExist(long lngmId) {
            return base.Channel.SubjectRelation_IsExist(lngmId);
        }
        
        public bool SubjectRelation_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation) {
            return base.Channel.SubjectRelation_AddNewRecordBySql2(objSubjectRelation);
        }
        
        public bool SubjectRelation_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation) {
            return base.Channel.SubjectRelation_UpdateBySql2(objSubjectRelation);
        }
        
        public bool SubjectRelation_DelRecord(long lngmId) {
            return base.Channel.SubjectRelation_DelRecord(lngmId);
        }
        
        public bool SubjectRelation_DelSubjectRelations(string[] arrStdId) {
            return base.Channel.SubjectRelation_DelSubjectRelations(arrStdId);
        }
        
        public GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceSubjectRelation.clsSubjectRelationEN objSubjectRelation) {
            return base.Channel.ExposeLogicClass(objSubjectRelation);
        }
    }
}
