//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxRelaOfPotenceAndSymbol.QxRelaOfPotenceAndSymbolServiceSoap")]
    public interface QxRelaOfPotenceAndSymbolServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxRelaOfPotenceAndSymbol_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbol(ref GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetObjByRelaMid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN QxRelaOfPotenceAndSymbol_GetObjByRelaMid(long lngRelaMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbolV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbolV(ref GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] QxRelaOfPotenceAndSymbol_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] QxRelaOfPotenceAndSymbol_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long QxRelaOfPotenceAndSymbol_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN QxRelaOfPotenceAndSymbol_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByRelaMid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByRelaMid(long lngRelaMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxRelaOfPotenceAndSymbol_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_IsExist(long lngRelaMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql2ByJSON(string strQxRelaOfPotenceAndSymbolJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_AddNewRecordBySql2WithReturnKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxRelaOfPotenceAndSymbol_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql_XML(string strQxRelaOfPotenceAndSymbolObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_UpdateBySql2ByJSON(string strQxRelaOfPotenceAndSymbolJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxRelaOfPotenceAndSymbol_UpdateBySql_XML(string strQxRelaOfPotenceAndSymbolObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxRelaOfPotenceAndSymbol_DelRecord(long lngRelaMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbols", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbols(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbolsByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbolsByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxRelaOfPotenceAndSymbol_SerializeObjToXMLStr(long lngRelaMid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxRelaOfPotenceAndSymbol_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxRelaOfPotenceAndSymbol_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxRelaOfPotenceAndSymbol_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxRelaOfPotenceAndSymbolEN : clsEntityBase2 {
        
        private long relaMidField;
        
        private string potenceIdField;
        
        private string symbolForProgrammeField;
        
        private string symbolNameField;
        
        private string memoField;
        
        private string qxPrjIdField;
        
        private string updDateField;
        
        private string updUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long RelaMid {
            get {
                return this.relaMidField;
            }
            set {
                this.relaMidField = value;
                this.RaisePropertyChanged("RelaMid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PotenceId {
            get {
                return this.potenceIdField;
            }
            set {
                this.potenceIdField = value;
                this.RaisePropertyChanged("PotenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SymbolForProgramme {
            get {
                return this.symbolForProgrammeField;
            }
            set {
                this.symbolForProgrammeField = value;
                this.RaisePropertyChanged("SymbolForProgramme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SymbolName {
            get {
                return this.symbolNameField;
            }
            set {
                this.symbolNameField = value;
                this.RaisePropertyChanged("SymbolName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UpdDate {
            get {
                return this.updDateField;
            }
            set {
                this.updDateField = value;
                this.RaisePropertyChanged("UpdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UpdUserId {
            get {
                return this.updUserIdField;
            }
            set {
                this.updUserIdField = value;
                this.RaisePropertyChanged("UpdUserId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxRelaOfPotenceAndSymbolEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxRelaOfPotenceAndSymbolServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.QxRelaOfPotenceAndSymbolServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxRelaOfPotenceAndSymbolServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.QxRelaOfPotenceAndSymbolServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.QxRelaOfPotenceAndSymbolServiceSoap {
        
        public QxRelaOfPotenceAndSymbolServiceSoapClient() {
        }
        
        public QxRelaOfPotenceAndSymbolServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxRelaOfPotenceAndSymbolServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxRelaOfPotenceAndSymbolServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxRelaOfPotenceAndSymbolServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSet(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxRelaOfPotenceAndSymbol_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxRelaOfPotenceAndSymbol_GetDataSetV(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetDataSetV(strWhereCond);
        }
        
        public bool QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbol(ref GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbol(ref objQxRelaOfPotenceAndSymbolEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN QxRelaOfPotenceAndSymbol_GetObjByRelaMid(long lngRelaMid) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetObjByRelaMid(lngRelaMid);
        }
        
        public bool QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbolV(ref GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetQxRelaOfPotenceAndSymbolV(ref objQxRelaOfPotenceAndSymbolEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] QxRelaOfPotenceAndSymbol_GetObjLst(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN[] QxRelaOfPotenceAndSymbol_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public long QxRelaOfPotenceAndSymbol_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN QxRelaOfPotenceAndSymbol_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByRelaMid(long lngRelaMid) {
            return base.Channel.GetJSONObjByRelaMid(lngRelaMid);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxRelaOfPotenceAndSymbol_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxRelaOfPotenceAndSymbol_IsExistRecord(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_IsExistRecord(strWhereCond);
        }
        
        public bool QxRelaOfPotenceAndSymbol_IsExist(long lngRelaMid) {
            return base.Channel.QxRelaOfPotenceAndSymbol_IsExist(lngRelaMid);
        }
        
        public bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.QxRelaOfPotenceAndSymbol_AddNewRecordBySql2(objQxRelaOfPotenceAndSymbolEN);
        }
        
        public bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql2ByJSON(string strQxRelaOfPotenceAndSymbolJSONObj) {
            return base.Channel.QxRelaOfPotenceAndSymbol_AddNewRecordBySql2ByJSON(strQxRelaOfPotenceAndSymbolJSONObj);
        }
        
        public string QxRelaOfPotenceAndSymbol_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.QxRelaOfPotenceAndSymbol_AddNewRecordBySql2WithReturnKey(objQxRelaOfPotenceAndSymbolEN);
        }
        
        public bool QxRelaOfPotenceAndSymbol_AddNewRecordBySql_XML(string strQxRelaOfPotenceAndSymbolObjXml) {
            return base.Channel.QxRelaOfPotenceAndSymbol_AddNewRecordBySql_XML(strQxRelaOfPotenceAndSymbolObjXml);
        }
        
        public bool QxRelaOfPotenceAndSymbol_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.QxRelaOfPotenceAndSymbol_UpdateBySql2(objQxRelaOfPotenceAndSymbolEN);
        }
        
        public bool QxRelaOfPotenceAndSymbol_UpdateBySql2ByJSON(string strQxRelaOfPotenceAndSymbolJSONObj) {
            return base.Channel.QxRelaOfPotenceAndSymbol_UpdateBySql2ByJSON(strQxRelaOfPotenceAndSymbolJSONObj);
        }
        
        public bool QxRelaOfPotenceAndSymbol_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN, string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_UpdateBySqlWithCondition(objQxRelaOfPotenceAndSymbolEN, strWhereCond);
        }
        
        public bool QxRelaOfPotenceAndSymbol_UpdateBySql_XML(string strQxRelaOfPotenceAndSymbolObjXml) {
            return base.Channel.QxRelaOfPotenceAndSymbol_UpdateBySql_XML(strQxRelaOfPotenceAndSymbolObjXml);
        }
        
        public int QxRelaOfPotenceAndSymbol_DelRecord(long lngRelaMid) {
            return base.Channel.QxRelaOfPotenceAndSymbol_DelRecord(lngRelaMid);
        }
        
        public int QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbols(string strJSON4Keys) {
            return base.Channel.QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbols(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbolsByCond(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_DelQxRelaOfPotenceAndSymbolsByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxRelaOfPotenceAndSymbol.clsQxRelaOfPotenceAndSymbolEN objQxRelaOfPotenceAndSymbolEN) {
            return base.Channel.ExposeLogicClass(objQxRelaOfPotenceAndSymbolEN);
        }
        
        public string QxRelaOfPotenceAndSymbol_SerializeObjToXMLStr(long lngRelaMid) {
            return base.Channel.QxRelaOfPotenceAndSymbol_SerializeObjToXMLStr(lngRelaMid);
        }
        
        public string QxRelaOfPotenceAndSymbol_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxRelaOfPotenceAndSymbol_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxRelaOfPotenceAndSymbol_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
