//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxUserDownLoadLog.QxUserDownLoadLogServiceSoap")]
    public interface QxUserDownLoadLogServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserDownLoadLog_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserDownLoadLog_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserDownLoadLog_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserDownLoadLog_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetQxUserDownLoadLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_GetQxUserDownLoadLog(ref GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetObjByUserDownLoadLogId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN QxUserDownLoadLog_GetObjByUserDownLoadLogId(string strUserDownLoadLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetQxUserDownLoadLogV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_GetQxUserDownLoadLogV(ref GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] QxUserDownLoadLog_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] QxUserDownLoadLog_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN QxUserDownLoadLog_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjByUserDownLoadLogId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjByUserDownLoadLogId(string strUserDownLoadLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserDownLoadLog_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_IsExist(string strUserDownLoadLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_GetMaxStrIdByPrefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_GetMaxStrIdByPrefix(string strPrefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_AddNewRecordBySql2ByJSON(string strQxUserDownLoadLogJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_AddNewRecordBySql_XML(string strQxUserDownLoadLogObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_UpdateBySql2ByJSON(string strQxUserDownLoadLogJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserDownLoadLog_UpdateBySql_XML(string strQxUserDownLoadLogObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserDownLoadLog_DelRecord(string strUserDownLoadLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_DelQxUserDownLoadLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserDownLoadLog_DelQxUserDownLoadLogs(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_DelQxUserDownLoadLogsByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserDownLoadLog_DelQxUserDownLoadLogsByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_SerializeObjToXMLStr(string strUserDownLoadLogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserDownLoadLog_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserDownLoadLog_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxUserDownLoadLogEN : clsEntityBase2 {
        
        private string userDownLoadLogIdField;
        
        private string userIdField;
        
        private string prjSiteIdField;
        
        private string downLownDateField;
        
        private bool isSuccessField;
        
        private string logInfoField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserDownLoadLogId {
            get {
                return this.userDownLoadLogIdField;
            }
            set {
                this.userDownLoadLogIdField = value;
                this.RaisePropertyChanged("UserDownLoadLogId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrjSiteId {
            get {
                return this.prjSiteIdField;
            }
            set {
                this.prjSiteIdField = value;
                this.RaisePropertyChanged("PrjSiteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DownLownDate {
            get {
                return this.downLownDateField;
            }
            set {
                this.downLownDateField = value;
                this.RaisePropertyChanged("DownLownDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LogInfo {
            get {
                return this.logInfoField;
            }
            set {
                this.logInfoField = value;
                this.RaisePropertyChanged("LogInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxUserDownLoadLogEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxUserDownLoadLogServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.QxUserDownLoadLogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxUserDownLoadLogServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.QxUserDownLoadLogServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.QxUserDownLoadLogServiceSoap {
        
        public QxUserDownLoadLogServiceSoapClient() {
        }
        
        public QxUserDownLoadLogServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxUserDownLoadLogServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserDownLoadLogServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserDownLoadLogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxUserDownLoadLog_GetDataSet(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxUserDownLoadLog_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxUserDownLoadLog_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxUserDownLoadLog_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxUserDownLoadLog_GetDataSetV(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetDataSetV(strWhereCond);
        }
        
        public bool QxUserDownLoadLog_GetQxUserDownLoadLog(ref GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN) {
            return base.Channel.QxUserDownLoadLog_GetQxUserDownLoadLog(ref objQxUserDownLoadLogEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN QxUserDownLoadLog_GetObjByUserDownLoadLogId(string strUserDownLoadLogId) {
            return base.Channel.QxUserDownLoadLog_GetObjByUserDownLoadLogId(strUserDownLoadLogId);
        }
        
        public bool QxUserDownLoadLog_GetQxUserDownLoadLogV(ref GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN) {
            return base.Channel.QxUserDownLoadLog_GetQxUserDownLoadLogV(ref objQxUserDownLoadLogEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] QxUserDownLoadLog_GetObjLst(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN[] QxUserDownLoadLog_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public string QxUserDownLoadLog_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN QxUserDownLoadLog_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjByUserDownLoadLogId(string strUserDownLoadLogId) {
            return base.Channel.GetJSONObjByUserDownLoadLogId(strUserDownLoadLogId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxUserDownLoadLog_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxUserDownLoadLog_IsExistRecord(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_IsExistRecord(strWhereCond);
        }
        
        public bool QxUserDownLoadLog_IsExist(string strUserDownLoadLogId) {
            return base.Channel.QxUserDownLoadLog_IsExist(strUserDownLoadLogId);
        }
        
        public string QxUserDownLoadLog_GetMaxStrId() {
            return base.Channel.QxUserDownLoadLog_GetMaxStrId();
        }
        
        public string QxUserDownLoadLog_GetMaxStrIdByPrefix(string strPrefix) {
            return base.Channel.QxUserDownLoadLog_GetMaxStrIdByPrefix(strPrefix);
        }
        
        public bool QxUserDownLoadLog_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN) {
            return base.Channel.QxUserDownLoadLog_AddNewRecordBySql2(objQxUserDownLoadLogEN);
        }
        
        public bool QxUserDownLoadLog_AddNewRecordBySql2ByJSON(string strQxUserDownLoadLogJSONObj) {
            return base.Channel.QxUserDownLoadLog_AddNewRecordBySql2ByJSON(strQxUserDownLoadLogJSONObj);
        }
        
        public bool QxUserDownLoadLog_AddNewRecordBySql_XML(string strQxUserDownLoadLogObjXml) {
            return base.Channel.QxUserDownLoadLog_AddNewRecordBySql_XML(strQxUserDownLoadLogObjXml);
        }
        
        public bool QxUserDownLoadLog_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN) {
            return base.Channel.QxUserDownLoadLog_UpdateBySql2(objQxUserDownLoadLogEN);
        }
        
        public bool QxUserDownLoadLog_UpdateBySql2ByJSON(string strQxUserDownLoadLogJSONObj) {
            return base.Channel.QxUserDownLoadLog_UpdateBySql2ByJSON(strQxUserDownLoadLogJSONObj);
        }
        
        public bool QxUserDownLoadLog_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN, string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_UpdateBySqlWithCondition(objQxUserDownLoadLogEN, strWhereCond);
        }
        
        public bool QxUserDownLoadLog_UpdateBySql_XML(string strQxUserDownLoadLogObjXml) {
            return base.Channel.QxUserDownLoadLog_UpdateBySql_XML(strQxUserDownLoadLogObjXml);
        }
        
        public int QxUserDownLoadLog_DelRecord(string strUserDownLoadLogId) {
            return base.Channel.QxUserDownLoadLog_DelRecord(strUserDownLoadLogId);
        }
        
        public int QxUserDownLoadLog_DelQxUserDownLoadLogs(string strJSON4Keys) {
            return base.Channel.QxUserDownLoadLog_DelQxUserDownLoadLogs(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxUserDownLoadLog_DelQxUserDownLoadLogsByCond(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_DelQxUserDownLoadLogsByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserDownLoadLog.clsQxUserDownLoadLogEN objQxUserDownLoadLogEN) {
            return base.Channel.ExposeLogicClass(objQxUserDownLoadLogEN);
        }
        
        public string QxUserDownLoadLog_SerializeObjToXMLStr(string strUserDownLoadLogId) {
            return base.Channel.QxUserDownLoadLog_SerializeObjToXMLStr(strUserDownLoadLogId);
        }
        
        public string QxUserDownLoadLog_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxUserDownLoadLog_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserDownLoadLog_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
