//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQxUserGroupPotence.QxUserGroupPotenceServiceSoap")]
    public interface QxUserGroupPotenceServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupPotence_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetTopDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupPotence_GetTopDataSet(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetDataSetByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupPotence_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QxUserGroupPotence_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetQxUserGroupPotence", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_GetQxUserGroupPotence(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN QxUserGroupPotence_GetObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetQxUserGroupPotenceV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_GetQxUserGroupPotenceV(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] QxUserGroupPotence_GetObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetTopObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] QxUserGroupPotence_GetTopObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetFirstID_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        long QxUserGroupPotence_GetFirstID_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_GetFirstObj_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN QxUserGroupPotence_GetFirstObj_S(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjBymId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjBymId(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstJSONObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetFirstJSONObj(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLst(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopJSONObjLst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetTopJSONObjLst(int intTopSize, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByPager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJSONObjLstByRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_funGetRecCountByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupPotence_funGetRecCountByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_IsExistRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_IsExistRecord(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_AddNewRecordBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_AddNewRecordBySql2ByJSON(string strQxUserGroupPotenceJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_AddNewRecordBySql2WithReturnKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupPotence_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_AddNewRecordBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_AddNewRecordBySql_XML(string strQxUserGroupPotenceObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_UpdateBySql2ByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_UpdateBySql2ByJSON(string strQxUserGroupPotenceJSONObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_UpdateBySqlWithCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN, string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_UpdateBySql_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool QxUserGroupPotence_UpdateBySql_XML(string strQxUserGroupPotenceObjXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupPotence_DelRecord(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_DelQxUserGroupPotences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupPotence_DelQxUserGroupPotences(string strJSON4Keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelRecordsByJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int DelRecordsByJSON(string strKeyIdLst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_DelQxUserGroupPotencesByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int QxUserGroupPotence_DelQxUserGroupPotencesByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_SerializeObjToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupPotence_SerializeObjToXMLStr(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_SerializeObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupPotence_SerializeObjLstToXMLStr(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QxUserGroupPotence_SerializeTopObjLstToXMLStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string QxUserGroupPotence_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxUserGroupPotenceEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string userIdField;
        
        private string groupIdField;
        
        private string roleIdField;
        
        private string qxPrjIdField;
        
        private string potenceIdField;
        
        private long relaMidField;
        
        private string memoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("GroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QxPrjId {
            get {
                return this.qxPrjIdField;
            }
            set {
                this.qxPrjIdField = value;
                this.RaisePropertyChanged("QxPrjId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PotenceId {
            get {
                return this.potenceIdField;
            }
            set {
                this.potenceIdField = value;
                this.RaisePropertyChanged("PotenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long RelaMid {
            get {
                return this.relaMidField;
            }
            set {
                this.relaMidField = value;
                this.RaisePropertyChanged("RelaMid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxUserGroupPotenceEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sf_UpdFldSetStrField;
        
        private int intTagField;
        
        private string strTagField;
        
        private string checkedField;
        
        private bool isCheckPropertyField;
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sf_UpdFldSetStr {
            get {
                return this.sf_UpdFldSetStrField;
            }
            set {
                this.sf_UpdFldSetStrField = value;
                this.RaisePropertyChanged("sf_UpdFldSetStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("Checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QxUserGroupPotenceServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.QxUserGroupPotenceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QxUserGroupPotenceServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.QxUserGroupPotenceServiceSoap>, GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.QxUserGroupPotenceServiceSoap {
        
        public QxUserGroupPotenceServiceSoapClient() {
        }
        
        public QxUserGroupPotenceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QxUserGroupPotenceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserGroupPotenceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QxUserGroupPotenceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QxUserGroupPotence_GetDataSet(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet QxUserGroupPotence_GetTopDataSet(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetTopDataSet(intTopSize, strWhereCond);
        }
        
        public System.Data.DataSet QxUserGroupPotence_GetDataSetByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.QxUserGroupPotence_GetDataSetByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public System.Data.DataSet QxUserGroupPotence_GetDataSetV(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetDataSetV(strWhereCond);
        }
        
        public bool QxUserGroupPotence_GetQxUserGroupPotence(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.QxUserGroupPotence_GetQxUserGroupPotence(ref objQxUserGroupPotenceEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN QxUserGroupPotence_GetObjBymId(long lngmId) {
            return base.Channel.QxUserGroupPotence_GetObjBymId(lngmId);
        }
        
        public bool QxUserGroupPotence_GetQxUserGroupPotenceV(ref GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.QxUserGroupPotence_GetQxUserGroupPotenceV(ref objQxUserGroupPotenceEN);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] QxUserGroupPotence_GetObjLst(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetObjLst(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] GetObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN[] QxUserGroupPotence_GetTopObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetTopObjLst(intTopSize, strWhereCond);
        }
        
        public long QxUserGroupPotence_GetFirstID_S(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetFirstID_S(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN QxUserGroupPotence_GetFirstObj_S(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_GetFirstObj_S(strWhereCond);
        }
        
        public string GetJSONObjBymId(long lngmId) {
            return base.Channel.GetJSONObjBymId(lngmId);
        }
        
        public string GetFirstJSONObj(string strWhereCond) {
            return base.Channel.GetFirstJSONObj(strWhereCond);
        }
        
        public string GetJSONObjLst(string strWhereCond) {
            return base.Channel.GetJSONObjLst(strWhereCond);
        }
        
        public string GetTopJSONObjLst(int intTopSize, string strWhereCond) {
            return base.Channel.GetTopJSONObjLst(intTopSize, strWhereCond);
        }
        
        public string GetJSONObjLstByPager(int intPageIndex, int intPageSize, string strWhereCond, string strOrderBy) {
            return base.Channel.GetJSONObjLstByPager(intPageIndex, intPageSize, strWhereCond, strOrderBy);
        }
        
        public string GetJSONObjLstByRange(string strWhereCond, string strOrderBy, int intMinNum, int intMaxNum) {
            return base.Channel.GetJSONObjLstByRange(strWhereCond, strOrderBy, intMinNum, intMaxNum);
        }
        
        public int QxUserGroupPotence_funGetRecCountByCond(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_funGetRecCountByCond(strWhereCond);
        }
        
        public bool QxUserGroupPotence_IsExistRecord(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_IsExistRecord(strWhereCond);
        }
        
        public bool QxUserGroupPotence_IsExist(long lngmId) {
            return base.Channel.QxUserGroupPotence_IsExist(lngmId);
        }
        
        public bool QxUserGroupPotence_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.QxUserGroupPotence_AddNewRecordBySql2(objQxUserGroupPotenceEN);
        }
        
        public bool QxUserGroupPotence_AddNewRecordBySql2ByJSON(string strQxUserGroupPotenceJSONObj) {
            return base.Channel.QxUserGroupPotence_AddNewRecordBySql2ByJSON(strQxUserGroupPotenceJSONObj);
        }
        
        public string QxUserGroupPotence_AddNewRecordBySql2WithReturnKey(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.QxUserGroupPotence_AddNewRecordBySql2WithReturnKey(objQxUserGroupPotenceEN);
        }
        
        public bool QxUserGroupPotence_AddNewRecordBySql_XML(string strQxUserGroupPotenceObjXml) {
            return base.Channel.QxUserGroupPotence_AddNewRecordBySql_XML(strQxUserGroupPotenceObjXml);
        }
        
        public bool QxUserGroupPotence_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.QxUserGroupPotence_UpdateBySql2(objQxUserGroupPotenceEN);
        }
        
        public bool QxUserGroupPotence_UpdateBySql2ByJSON(string strQxUserGroupPotenceJSONObj) {
            return base.Channel.QxUserGroupPotence_UpdateBySql2ByJSON(strQxUserGroupPotenceJSONObj);
        }
        
        public bool QxUserGroupPotence_UpdateBySqlWithCondition(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN, string strWhereCond) {
            return base.Channel.QxUserGroupPotence_UpdateBySqlWithCondition(objQxUserGroupPotenceEN, strWhereCond);
        }
        
        public bool QxUserGroupPotence_UpdateBySql_XML(string strQxUserGroupPotenceObjXml) {
            return base.Channel.QxUserGroupPotence_UpdateBySql_XML(strQxUserGroupPotenceObjXml);
        }
        
        public int QxUserGroupPotence_DelRecord(long lngmId) {
            return base.Channel.QxUserGroupPotence_DelRecord(lngmId);
        }
        
        public int QxUserGroupPotence_DelQxUserGroupPotences(string strJSON4Keys) {
            return base.Channel.QxUserGroupPotence_DelQxUserGroupPotences(strJSON4Keys);
        }
        
        public int DelRecordsByJSON(string strKeyIdLst) {
            return base.Channel.DelRecordsByJSON(strKeyIdLst);
        }
        
        public int QxUserGroupPotence_DelQxUserGroupPotencesByCond(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_DelQxUserGroupPotencesByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceQxUserGroupPotence.clsQxUserGroupPotenceEN objQxUserGroupPotenceEN) {
            return base.Channel.ExposeLogicClass(objQxUserGroupPotenceEN);
        }
        
        public string QxUserGroupPotence_SerializeObjToXMLStr(long lngmId) {
            return base.Channel.QxUserGroupPotence_SerializeObjToXMLStr(lngmId);
        }
        
        public string QxUserGroupPotence_SerializeObjLstToXMLStr(string strWhereCond) {
            return base.Channel.QxUserGroupPotence_SerializeObjLstToXMLStr(strWhereCond);
        }
        
        public string QxUserGroupPotence_SerializeTopObjLstToXMLStr(int intTopSize, string strWhereCond) {
            return base.Channel.QxUserGroupPotence_SerializeTopObjLstToXMLStr(intTopSize, strWhereCond);
        }
    }
}
