//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.586
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralPlatform4WS.ServiceReferenceRoleMenus {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRoleMenus.RoleMenusServiceSoap")]
    public interface RoleMenusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RoleMenus_GetDataSet(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_GetDataSetV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RoleMenus_GetDataSetV(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_GetQxRoleMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_GetQxRoleMenus(ref GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_GetQxRoleMenusV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_GetQxRoleMenusV(ref GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_IsExistRecordByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_IsExistRecordByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_IsExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_IsExist(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_GetMaxStrId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        string RoleMenus_GetMaxStrId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_AddNewRecordBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_UpdateBySql2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_DelRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_DelRecord(long lngmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_DelRoleMenuss", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        bool RoleMenus_DelRoleMenuss(string[] arrStdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoleMenus_DelRoleMenussByCond", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        int RoleMenus_DelRoleMenussByCond(string strWhereCond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExposeLogicClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clsEntityBase2))]
        GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsQxRoleMenusEN : clsEntityBase2 {
        
        private long mIdField;
        
        private string roleIdField;
        
        private string prjIdField;
        
        private string menuIdField;
        
        private bool isDispField;
        
        private string memoField;
        
        private int intTagField;
        
        private string strTagField;
        
        private bool isCheckPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mId {
            get {
                return this.mIdField;
            }
            set {
                this.mIdField = value;
                this.RaisePropertyChanged("mId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrjId {
            get {
                return this.prjIdField;
            }
            set {
                this.prjIdField = value;
                this.RaisePropertyChanged(clsQxProjectsEN.con_QxPrjId);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MenuId {
            get {
                return this.menuIdField;
            }
            set {
                this.menuIdField = value;
                this.RaisePropertyChanged("MenuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsDisp {
            get {
                return this.isDispField;
            }
            set {
                this.isDispField = value;
                this.RaisePropertyChanged("IsDisp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IntTag {
            get {
                return this.intTagField;
            }
            set {
                this.intTagField = value;
                this.RaisePropertyChanged("IntTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StrTag {
            get {
                return this.strTagField;
            }
            set {
                this.strTagField = value;
                this.RaisePropertyChanged("StrTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsCheckProperty {
            get {
                return this.isCheckPropertyField;
            }
            set {
                this.isCheckPropertyField = value;
                this.RaisePropertyChanged("IsCheckProperty");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsQxRoleMenusEN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEntityBase2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errNoField;
        
        private string dispErrMsgField;
        
        private string[] tabKeyFldNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrNo {
            get {
                return this.errNoField;
            }
            set {
                this.errNoField = value;
                this.RaisePropertyChanged("ErrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DispErrMsg {
            get {
                return this.dispErrMsgField;
            }
            set {
                this.dispErrMsgField = value;
                this.RaisePropertyChanged("DispErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] TabKeyFldNames {
            get {
                return this.tabKeyFldNamesField;
            }
            set {
                this.tabKeyFldNamesField = value;
                this.RaisePropertyChanged("TabKeyFldNames");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoleMenusServiceSoapChannel : GeneralPlatform4WS.ServiceReferenceRoleMenus.RoleMenusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleMenusServiceSoapClient : System.ServiceModel.ClientBase<GeneralPlatform4WS.ServiceReferenceRoleMenus.RoleMenusServiceSoap>, GeneralPlatform4WS.ServiceReferenceRoleMenus.RoleMenusServiceSoap {
        
        public RoleMenusServiceSoapClient() {
        }
        
        public RoleMenusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleMenusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleMenusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleMenusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet RoleMenus_GetDataSet(string strWhereCond) {
            return base.Channel.RoleMenus_GetDataSet(strWhereCond);
        }
        
        public System.Data.DataSet RoleMenus_GetDataSetV(string strWhereCond) {
            return base.Channel.RoleMenus_GetDataSetV(strWhereCond);
        }
        
        public bool RoleMenus_GetQxRoleMenus(ref GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus) {
            return base.Channel.RoleMenus_GetQxRoleMenus(ref objRoleMenus);
        }
        
        public bool RoleMenus_GetQxRoleMenusV(ref GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus) {
            return base.Channel.RoleMenus_GetQxRoleMenusV(ref objRoleMenus);
        }
        
        public bool RoleMenus_IsExistRecordByCond(string strWhereCond) {
            return base.Channel.RoleMenus_IsExistRecordByCond(strWhereCond);
        }
        
        public bool RoleMenus_IsExist(long lngmId) {
            return base.Channel.RoleMenus_IsExist(lngmId);
        }
        
        public string RoleMenus_GetMaxStrId() {
            return base.Channel.RoleMenus_GetMaxStrId();
        }
        
        public bool RoleMenus_AddNewRecordBySql2(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus) {
            return base.Channel.RoleMenus_AddNewRecordBySql2(objRoleMenus);
        }
        
        public bool RoleMenus_UpdateBySql2(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus) {
            return base.Channel.RoleMenus_UpdateBySql2(objRoleMenus);
        }
        
        public bool RoleMenus_DelRecord(long lngmId) {
            return base.Channel.RoleMenus_DelRecord(lngmId);
        }
        
        public bool RoleMenus_DelRoleMenuss(string[] arrStdId) {
            return base.Channel.RoleMenus_DelRoleMenuss(arrStdId);
        }
        
        public int RoleMenus_DelRoleMenussByCond(string strWhereCond) {
            return base.Channel.RoleMenus_DelRoleMenussByCond(strWhereCond);
        }
        
        public GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN ExposeLogicClass(GeneralPlatform4WS.ServiceReferenceRoleMenus.clsQxRoleMenusEN objRoleMenus) {
            return base.Channel.ExposeLogicClass(objRoleMenus);
        }
    }
}
